version: '3.7'

services:

    godev:
        # The DRLMv3 development environment with:
        # tmux - nvim - git - gitflow 
        image: godev:1.11.5
        container_name: godev
#        environment:
        volumes:
            - ${PWD}/files/golang/goroot:/usr/local/go
            - ${PWD}/files/golang/protoc:/usr/local/protoc
            - ${PWD}/files/golang/gopath:${HOME}/go
            - ${PWD}/files/dots:${HOME}/dots
            - ${PWD}/files/vimplug:${HOME}/.vim/plugged 
            - ${PWD}/files/tls:/tls
#        ports:
        networks:
            - dr3dev
#        command: bash -c "tmux new -s DRLMv3_DevEnv 'nvim go'"
        command: bash 

networks:
    dr3dev:
        external: true
