version: '3.7'

services:

    godev:
        # The DRLMv3 development environment with:
        # tmux - nvim - vscode - git - gitflow 
        image: godev-vscode:1.11.5
        environment:
            - DISPLAY=${DISPLAY}
        ipc: host
        volumes:
            - ${PWD}/files/golang/goroot:/usr/local/go
            - ${PWD}/files/golang/protoc:/usr/local/protoc
            - ${PWD}/files/golang/gopath:${HOME}/go
            - ${PWD}/files/dots:${HOME}/dots
            - ${PWD}/files/vscode:${HOME}/.vscode-oss/
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/shm:/dev/shm
        networks:
            - dr3env
#        ports:
#        command: code ${HOME}/go

networks:
    dr3env:
        external: true

